version: '2'
services:
  applications:
    image: tianon/true
    container_name: applications
    volumes:
        - ${APPLICATION}:/var/www
  apache:
    image: wilbertjoosen/docker_hemovida_apache
    container_name: apache
    volumes_from:
        - applications
    links:
        - "php"
    volumes:
        - ./data/apache/logs:/var/log/apache2
        - ./data/apache/sites:/etc/apache2/sites-available
    depends_on:
        - php
    ports:
      - "80:80"
    networks:
      - app  
  jenkins:
    image: wilbertjoosen/docker_hemovida_jenkins:latest
    #build:
    #    context: jenkins
    #    dockerfile: "Dockerfile"
    container_name: jenkins
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - ./data/jenkins:/var/jenkins_home
    networks:
      - app  
    extra_hosts:
      - "hemovida.local.saude.gov.br:172.19.0.6"
      - "hemovida.desenvolvimento.saude.gov:10.1.1.144"
  jboss-64:
    image: kengsarun/jboss-eap-6
    container_name: jboss-64
    ports:
      - '8081:8080'
      - '9990:9990'
    volumes:
      - ./data/jboss-64/deployments:/opt/jboss/jboss-eap/standalone/deployments/
      - ./data/jboss-64/configuration:/opt/jboss/jboss-eap/standalone/configuration/
      - ./data/jboss-64/modules:/opt/jboss/jboss-eap/modules/
    networks:
      - app  
    extra_hosts:
      - "srvoradf20-scan.saude.gov:172.25.61.150"
  php:
    image: wilbertjoosen/docker_hemovida_php:latest
    container_name: php
    volumes_from:
      - applications
    volumes:
      - ./data/php/conf/:/usr/local/etc/php/conf.d/
      - ./data/php/log/:/var/log/
      - ./data/php/include_path:/var/www/include_path
    depends_on:
      - workspace
    expose:
      - "9000"
    extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "srvoradf20-scan.saude.gov:172.25.61.150"
        - "scpaweb-ws-homologacao.saude.gov.br:189.28.129.73"
    networks:
      - app
  workspace:
    image: wilbertjoosen/docker_hemovida_workspace
    container_name: workspace
    volumes_from:
      - applications
    tty: true
    networks:
      - app
networks:
    app:
        driver: "bridge"
